var addButton  = document.getElementsByClassName('btn-block');
var removeBtn  = document.getElementsByClassName('remove-btn');
var purchaseBtn  = document.getElementsByClassName('btn-purchase')[0];
var Qty  = document.getElementsByClassName('cart-qty-input');


// ADD TO CART SECTION
for (var i = 0; i < addButton.length; i++) {
    add = addButton[i];
    add.addEventListener('click', addToCart);
}

function addToCart(event){
    button = event.target;
    item = button.parentElement;
    title = item.getElementsByClassName('item-title')[0].innerText;
    image = item.getElementsByClassName('item-image')[0].src;
    price = item.getElementsByClassName('item-price')[0].innerText;
    addItemtoCart(title, image, price);
}

function addItemtoCart(title, image, price){
    var cartRow = document.createElement('div');
        cartRow.classList.add('cart-row');

    var cartItems = document.getElementsByClassName('cart-items')[0];

    var cartItemsNames = cartItems.getElementsByClassName('cart-item-title');
        for (var i = 0; i < cartItemsNames.length; i++) {
            if (cartItemsNames[i].innerText == title){
                alert('Item has already been added to Cart');
                return;
            }
        }
    var cartRowContent =   `<div class="cart-item col-4">
                                <img src="${image}" class="cart-item-image rounded" width="50" height="50" alt="">
                                <span class="cart-item-title">${title}</span>
                            </div>
                            <span class="cart-price col-3">${price}</span>
                            <div class="cart-quantity col-5">
                                <input type="number" value="1" class="cart-qty-input" name="" id="">
                                <button class="btn-danger remove-btn btn-sm">Remove</button>
                            </div>`
    cartRow.innerHTML = cartRowContent;
    cartItems.append(cartRow);

    //add Event Listeners to elements generated by JS
    cartRow.getElementsByClassName('remove-btn')[0].addEventListener('click', removeFromCart);
    cartRow.getElementsByClassName('cart-qty-input')[0].addEventListener('change', quantityChanged);

    updateTotalPrice();
}

// REMOVE FROM CART SECTION
for (var i = 0; i < removeBtn.length; i++) {
    remBtn = removeBtn[i];
    remBtn.addEventListener('click', removeFromCart);
}

function removeFromCart(event){
    var cartItemsContainer = document.getElementsByClassName('cart-items')[0];
    var cartRows = cartItemsContainer.getElementsByClassName('cart-row'); 
    button = event.target;
    button.parentElement.parentElement.remove();
    updateTotalPrice();

    if (cartItemsContainer.childElementCount == 0) {
        document.getElementsByClassName('total-price')[0].innerHTML = 'N0.00';
    }
}


// QUANTITY CHANGED SECTION 
for (var i = 0; i < Qty.length; i++) {
    Quantity = Qty[i];
    remBtn.addEventListener('change', quantityChanged);
}

function quantityChanged(event) {
    input = event.target;
    if (input.value <= 0){
        input.value = 1;
    }

    updateTotalPrice();
}


// "Purchase section"
purchaseBtn.addEventListener('click', purchaseClicked);

function purchaseClicked(){
    alert("Thank You! A pleasure doing business with you");
    var cartItems = document.getElementsByClassName('cart-items')[0];
        while (cartItems.hasChildNodes()) {
            cartItems.removeChild(cartItems.firstChild);
            document.getElementsByClassName('total-price')[0].innerHTML = 'N0.00';
        }
    updateTotalPrice();
}

// UPDATE CART TOTAL PRICE
function updateTotalPrice() {
    var cartItemsContainer = document.getElementsByClassName('cart-items')[0];
    var cartRows = cartItemsContainer.getElementsByClassName('cart-row'); //gets the children with that class as an array
    var total = 0;

    for (var i = 0; i < cartRows.length; i++) {
        var cartRow = cartRows[i];
        var itemPrice = cartRow.getElementsByClassName('cart-price')[0];
        var itemQty = cartRow.getElementsByClassName('cart-qty-input')[0];

        var price = parseFloat(itemPrice.innerText.replace("N", ""));
        var quantity = itemQty.value;
        total = total + (price * quantity);
        document.getElementsByClassName('total-price')[0].innerText = 'N' + total.toFixed(2);
        
    }

}


//Make Cart Responsive